-

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -10,10 +10,10 @@ set -e
 BUILD_DIR=$1
 CACHE_DIR=$2
 
-function error() {
-  echo "!$*" >&2
-  exit 1
-}
+# function error() {
+#   echo "!$*" >&2
+#   exit 1
+# }
 
 function topic() {
   echo "-----> $*"
